#pragma once

// Generated by docs/tools/generate_mir_pulse_family_contract.py.
// Edit mir_pulse_family_contract.json, then regenerate both language views.

#include <array>
#include <cstdint>

namespace smart_tempo::mir_pipeline {

enum class MirPulseRelation : std::uint8_t {
  quarter,
  one_third,
  half,
  two_thirds,
  three_quarters,
  equivalent,
  four_thirds,
  three_halves,
  double_time,
  triple,
  quadruple,
};

struct MirPulseRelationSpec {
  MirPulseRelation relation;
  std::uint8_t numerator;
  std::uint8_t denominator;
  const char* name;
};

inline constexpr std::array<MirPulseRelationSpec, 11>
    kMirPulseRelations{{
    {MirPulseRelation::quarter, 1u, 4u, "quarter"},
    {MirPulseRelation::one_third, 1u, 3u, "one_third"},
    {MirPulseRelation::half, 1u, 2u, "half"},
    {MirPulseRelation::two_thirds, 2u, 3u, "two_thirds"},
    {MirPulseRelation::three_quarters, 3u, 4u, "three_quarters"},
    {MirPulseRelation::equivalent, 1u, 1u, "equivalent"},
    {MirPulseRelation::four_thirds, 4u, 3u, "four_thirds"},
    {MirPulseRelation::three_halves, 3u, 2u, "three_halves"},
    {MirPulseRelation::double_time, 2u, 1u, "double_time"},
    {MirPulseRelation::triple, 3u, 1u, "triple"},
    {MirPulseRelation::quadruple, 4u, 1u, "quadruple"},
}};

[[nodiscard]] constexpr double mir_pulse_relation_multiplier(
    MirPulseRelation relation) noexcept {
  for (const auto& spec : kMirPulseRelations) {
    if (spec.relation == relation) {
      return static_cast<double>(spec.numerator) /
             static_cast<double>(spec.denominator);
    }
  }
  return 0.0;
}

[[nodiscard]] constexpr double mir_pulse_ratio(
    double candidateBpm, double anchorBpm) noexcept {
  return candidateBpm > 0.0 && anchorBpm > 0.0
             ? candidateBpm / anchorBpm
             : 0.0;
}

[[nodiscard]] constexpr bool mir_pulse_ratio_in_range(
    double candidateBpm, double anchorBpm, double minimumRatio,
    double maximumRatio) noexcept {
  if (!(candidateBpm > 0.0) || !(anchorBpm > 0.0) ||
      minimumRatio > maximumRatio) {
    return false;
  }
  const double ratio = mir_pulse_ratio(candidateBpm, anchorBpm);
  return ratio >= minimumRatio && ratio <= maximumRatio;
}

}  // namespace smart_tempo::mir_pipeline
