//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by foo_smart_tempo.rc
//
#define IDD_BPM_PREFERENCES             101
#define IDD_BPM_RESULT_DIALOG           103
#define IDD_BPM_MANUAL_DIALOG           105
#define IDD_BPM_PROGRESS_DIALOG         106
#define IDD_BPM_PREF_TAGGING            107
#define IDD_BPM_PREF_ALGO               108
#define IDD_BPM_OVERWRITE_PROMPT_DIALOG 109
#define IDD_BPM_ROUTING_IMPORT_DIALOG   110
#define IDD_BPM_PREF_GENRES             111
#define IDD_BPM_MEASURED_CANDIDATE_DIALOG 112
#define ID_BPM_RESULT_LIST              1006
#define ID_CONFIG_BPM_PRECISION         1012
#define ID_CONFIG_BPM_TAG               1021
#define ID_CONFIG_AUTO_WRITE_TAG        1025
#define ID_RESULT_BPM_TAG               1026
#define ID_BPM_MANUAL_TAP_BUTTON        1027
#define ID_BPM_MANUAL_UPDATE_TAG_BUTTON 1028
#define ID_BPM_MANUAL_BPM               1030
#define ID_BPM_MANUAL_RESET_BUTTON      1031
#define ID_MANUAL_BPM_TAG               1032
#define ID_DOUBLE_BPM_BUTTON            1033
#define ID_HALVE_BPM_BUTTON             1034
#define ID_BPM_PROGRESS_FILE            1036
#define ID_BPM_PROGRESS_TOTAL           1037
#define ID_BPM_PROGRESS_INFO            1038
#define ID_BPM_PROGRESS_PAUSE           1039
#define ID_BPM_PROGRESS_ABORT           1040
#define ID_RESULT_PREFERENCES_BUTTON    1041
#define ID_MANUAL_PREFERENCES_BUTTON    1042
#define ID_CONFIG_PREF_TABS         1052
#define ID_GROUP_TAGGING            1053
#define ID_BPM_MANUAL_TRACK_INFO      1056
#define ID_CONFIG_CONFIDENCE_TAG_NAME 1080
#define ID_CONFIG_WRITE_CONFIDENCE_TAG 1081
#define IDC_BPM_OVERWRITE_PROMPT_TEXT 1082
#define IDC_STATIC_CONFIDENCE_TAG    1083
#define ID_CONFIG_SMART_TEMPO_PLAYLIST_NAME 1084
#define ID_CONFIG_SMART_TEMPO_ROUTING_TAG 1085
#define IDC_LIST_GENRE_RULES         1086
#define IDC_EDIT_RULE_GENRES         1087
#define IDC_EDIT_RULE_MIN            1088
#define IDC_BTN_RULE_ADD             1090
#define IDC_BTN_RULE_UPDATE          1091
#define IDC_BTN_RULE_REMOVE          1092
#define IDC_BTN_RULE_UP              1093
#define IDC_BTN_RULE_DOWN            1094
#define IDC_BTN_ROUTING_IMPORT       1098
#define IDC_IMPORT_VALUES_LIST       1100
#define IDC_BTN_IMPORT_SELECT_ALL    1101
#define IDC_BTN_IMPORT_CLEAR_ALL     1102
#define IDC_STATIC_IMPORT_HINT       1103
#define ID_RESULT_MANUAL_BUTTON      1104
#define ID_CONFIG_VERBOSE_LOGGING    1114
#define IDC_BTN_RULE_IMPORT_CLIPBOARD 1115
#define IDC_BTN_RULE_EXPORT_CLIPBOARD 1116
#define ID_CONFIG_GENERIC_ANCHOR_TOKENS 1117
#define IDC_CHK_MANUAL_ALWAYS_ON_TOP 1121
#define ID_CONFIG_WORKER_MODE        1122
#define ID_CONFIG_CREATE_UNMATCHED_PLAYLIST 1123
#define ID_CONFIG_REVIEW_PLAYLIST_NAME 1124
#define ID_CONFIG_CREATE_REVIEW_PLAYLIST 1125
#define ID_RESULT_MEASURED_CANDIDATES_BUTTON 1126
#define IDC_MEASURED_CANDIDATE_LIST     1127
#define IDC_MEASURED_CANDIDATE_HINT     1128
#define IDC_METRONOME_GROUP             1129
#define IDC_METRONOME_STOP              1130
#define IDC_METRONOME_SYNC              1131
#define IDC_METRONOME_NUDGE_EARLIER     1133
#define IDC_METRONOME_NUDGE_LATER       1134
#define IDC_METRONOME_METER             1135
#define IDC_METRONOME_VOLUME            1136
#define IDC_METRONOME_STATUS            1137
#define IDC_MEASURED_CANDIDATE_FOOTNOTE 1138
#define ID_BPM_MANUAL_STABILITY         1139

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE        1140
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
